version: '3'

networks:
  default:
    external:
      name: webapp

services:
  nginx:
    image: nginx:stable-alpine
    container_name: LGA_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:rw
  
  